add_rules("mode.debug", "mode.release")

target("glfwppm")
    set_kind("moduleonly")
    set_languages("c++23")
    add_files("src/*.ixx", "src/**/*.ixx")
    add_options("native_win32")
    add_options("native_cocoa")
    add_options("native_x11")
    add_options("native_wayland")
    add_options("native_wgl")
    add_options("native_nsgl")
    add_options("native_glx")
    add_options("native_egl")
    add_options("native_osmesa")
    add_options("vulkan")
    add_options("vulkan-hpp")

    set_policy("build.c++.modules", true)
    add_packages("glfw")



option("native_win32")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_WIN32")
option_end()
option("native_cocoa")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_COCOA")
option_end()
option("native_x11")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_X11")
option_end()
option("native_wayland")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_WAYLAND")

option_end()
option("native_wgl")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_WGL")
option_end()
option("native_nsgl")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_NSGL")
option_end()
option("native_glx")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_GLX")
option_end()
option("native_egl")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_EGL")
option_end()
option("native_osmesa")
    set_default(false)
    set_showmenu(true)
    add_defines("GLFW_EXPOSE_NATIVE_OSMESA")
option_end()

option("vulkan")
    set_default(false)
    set_showmenu(true)
    add_defines("VK_VERSION_1_0")
option_end()
option("vulkan-hpp")
    set_default(false)
    set_showmenu(true)
    add_defines("VULKAN_HPP")
option_end()